### ISSUE TITLE
no content on the news article page

### ISSUE THREAD

**Issue by hayzull** [justinfujimoto/Web#13]
-suggestion,must fix before the product is released
-Firefox 43.01.4
-Expected: Content on the news article page
-Actual: The page only displays the Year Up logo and the two navigation bars
-Steps to reproduce: Add a news article to the page with a minimum of two and a maximum of five paragraphs with at least one image

**Comment by justinfujimoto** [comment]
Issue fixed: fcdaff7224c5ae22a8f57aabc76370822d9181fd
