### ISSUE TITLE
no images have a shadow effect

### ISSUE THREAD

**Issue by hayzull** [justinfujimoto/Web#14]
-minor,must fix before the product is released
-Firefox 43.0.4
-Expected: All images feature a shadow effect coordinated with background color
-Actual: No images have a shadow effect coordinated with background color
-Steps to reproduce: Create a shadow effect for the images

**Comment by justinfujimoto** [comment]
Issue resolved: f4984f94082cfe5285638c0147354b8bbc6bbd3d
