### ISSUE TITLE
live link to your YU email address

### ISSUE THREAD

**Issue by hayzull** [justinfujimoto/Web#2]
-Minimal and fix before releasing the product
-Firefox 43.0.4
-Expected: For every page to provide a live link to your YU email address
-Actual: Found on the pages, not a clickable link
-Steps to reproduce: Provide the clickable link to every single page

**Comment by justinfujimoto** [comment]
Issue fixed: c7b0f1816b9ffd753b9f4e8c0252bb5aa1e87238
