### ISSUE TITLE
Broken Year Up link

### ISSUE THREAD

**Issue by hayzull** [justinfujimoto/Web#4]
-loss of functionality, must be fixed immediately
-Firefox 43.0.4
-Expected: To be brought to the Year Up website after clicking the link
-Actual: Broken link, sends me to a file not found page
-Steps to reproduce: Fix the link in the html coding page

**Comment by justinfujimoto** [comment]
Fixed issue: 0203b629a562afdc371acf0be118a7217a83e1b0
